
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Jun 15 23:45:30 CEST 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int MASMAS = 29;
  public static final int DOSPUNTOS = 20;
  public static final int MENOSMENOS = 30;
  public static final int MULT = 33;
  public static final int CHAR = 5;
  public static final int MAI = 39;
  public static final int PUNTOYCOMA = 21;
  public static final int ENTERO = 49;
  public static final int CASE = 16;
  public static final int IGIG = 41;
  public static final int RESTA = 32;
  public static final int PC = 26;
  public static final int PA = 25;
  public static final int INT = 2;
  public static final int FOR = 11;
  public static final int AND = 44;
  public static final int CARACTER = 51;
  public static final int OR = 45;
  public static final int BOOL = 3;
  public static final int SUMA = 31;
  public static final int IG = 46;
  public static final int CC = 24;
  public static final int IF = 9;
  public static final int CA = 23;
  public static final int DIST = 42;
  public static final int EOF = 0;
  public static final int ASIG = 52;
  public static final int RETURN = 12;
  public static final int TRUE = 6;
  public static final int NEW = 47;
  public static final int error = 1;
  public static final int COMA = 22;
  public static final int MENOR = 38;
  public static final int MOD = 36;
  public static final int BREAK = 17;
  public static final int VOID = 13;
  public static final int SWITCH = 15;
  public static final int REAL = 50;
  public static final int MAYOR = 37;
  public static final int DIVE = 34;
  public static final int DIVD = 35;
  public static final int LLC = 28;
  public static final int NEG = 43;
  public static final int LLA = 27;
  public static final int ELSE = 10;
  public static final int PUNTO = 19;
  public static final int FUNC = 54;
  public static final int IDEN = 48;
  public static final int WHILE = 8;
  public static final int DEFAULT = 18;
  public static final int MEI = 40;
  public static final int FLOAT = 4;
  public static final int PROC = 53;
  public static final int FALSE = 7;
  public static final int STRUCT = 14;
}

