package ast;

public enum TipoE {
	AND, ASTERISCO, CAR, CORCHETES, DIST, DIVD, DIVE, ENT, FALSO, IDEN, IGIG, LLAMADAFUNC, 
	MAI, MAS, MAYOR, MEI, MENOR, MENOS, MOD, MUL, NEG, NEW, OR, PUNTO, REAL, RESTA, SUMA, VERDAD
}
